export const productFields = [
  'id',
  'picture',
  'product',
  'count',
  'year',
  'brand',
  'frame size',
  'wheel size',
  'rating',
  'category',
  'price',
  'Frame',
  'Fork',
  'Crankset',
  'Rear Derailleur',
  'Cassette',
  'Chain',
  'Wheelset',
  'Weight',
];

export const products = [
  {
    id: 0,
    picture: [10],
    product: 'Vitus Sommet 297 CRX Mountain Bike 2022',
    count: 1,
    year: 2022,
    color: 'Green',
    brand: 'Vitus',
    'frame size': 'XL',
    'wheel size': '29',
    rating: 5,
    category: 'mountain',
    price: 5499.99,
    Frame: 'Sommet T700 carbon front triangle',
    Fork: 'Fox 38 Float EVOL Factory Series 29',
    Crankset: 'Shimano XT M8100, 12 Speed, 32T Narrow WidChainring, 170mm Crank Length',
    'Rear Derailleur': 'Shimano XT M8100, 12 Speed, Shadow Plus, Long Cage',
    Cassette: null,
    Chain: 'KMC x10 10 Speed 114',
    Wheelset:
      "Nukeproof Horizon V2 Wheelset, 29' Front, 27.5' Rear, 32H, 6 Bolt, Boost 110mm x 15mm Front and 148mm x 12mm Rear Hub Spacing, Tubeless Ready",
    Weight: null,
  },
  {
    id: 3,
    picture: [30],
    product: 'Cube Aim Pro Hardtail Bike 2022',
    count: 5,
    year: 2022,
    color: 'Grey',
    brand: 'Cube',
    'frame size': 'XS',
    'wheel size': '27.5',
    rating: 5,
    category: 'mountain',
    price: 844,
    Frame:
      'Aluminium Lite, AMF, Double Butted, Internal Cable Routing, Tapered Head Tube, Flat Mount Brake, SIC Mount, FM Kickstand Mount',
    Fork: 'SR Suntour XCT, 100mm',
    Crankset: 'Shimano FC-M315, 36x22T',
    'Rear Derailleur': null,
    Cassette: 'Shimano CS-HG31, 11-34T',
    Chain: 'KMC Z8.3',
    Wheelset: null,
    Weight: 14.6,
  },
];

export const filteringBrandCurrent = 'Felt';
export const filteringProduct = {
  id: 14,
  picture: [110],
  product: 'Felt Broam 30 Gravel Bike 2021',
  count: 3,
  year: 2021,
  color: 'Blue',
  brand: 'Felt',
  'frame size': 'XL',
  'wheel size': '700c',
  rating: 4,
  category: 'road',
  price: 2105,
  Frame: 'Felt BROAM - Adventure | SuperLite Aluminium',
  Fork: 'Felt Gravel - Adventure | UHC Performance Carbon Fibre with Aluminium steerer tube',
  Crankset: 'Shimano GRX RX600, 46/30T',
  'Rear Derailleur': 'Shimano GRX RX810',
  Cassette: 'Shimano 105 HG700, 11-34T',
  Chain: null,
  Wheelset: 'Devox WheelRDS.A1 with Shimano RS470 12mm Thru-Axe hubs',
  Weight: 10.56,
};

export const sortingProduct = {
  id: 0,
  picture: [10],
  product: 'Vitus Sommet 297 CRX Mountain Bike 2022',
  count: 1,
  year: 2022,
  color: 'Green',
  brand: 'Vitus',
  'frame size': 'XL',
  'wheel size': '29',
  rating: 5,
  category: 'mountain',
  price: 5499.99,
  Frame: 'Sommet T700 carbon front triangle',
  Fork: 'Fox 38 Float EVOL Factory Series 29',
  Crankset: 'Shimano XT M8100, 12 Speed, 32T Narrow WidChainring, 170mm Crank Length',
  'Rear Derailleur': 'Shimano XT M8100, 12 Speed, Shadow Plus, Long Cage',
  Cassette: null,
  Chain: 'KMC x10 10 Speed 114',
  Wheelset:
    "Nukeproof Horizon V2 Wheelset, 29' Front, 27.5' Rear, 32H, 6 Bolt, Boost 110mm x 15mm Front and 148mm x 12mm Rear Hub Spacing, Tubeless Ready",
  Weight: null,
};

export const searchingProduct = {
  id: 19,
  picture: [150],
  product: 'Cinelli Veltrix Caliper 105 Road Bike 2020',
  count: 3,
  year: 2020,
  color: 'Blue',
  brand: 'Cinelli',
  'frame size': 'XL',
  'wheel size': '700c',
  rating: 4,
  category: 'road',
  price: 2404,
  Frame: 'Columbus Carbon Monocoque',
  Fork: "Columbus 1 1/8' - 1 1/2' Monocoque",
  Crankset: 'FSA Omega MX Chainset 34/50T',
  'Rear Derailleur': null,
  Cassette: 'Shimano 105 11x 11/32T',
  Chain: 'KMC 11x',
  Wheelset: 'Vision Team 30 TLR',
  Weight: 9,
};

export const colors = [
  'Green',
  'Purple',
  'Grey',
  'Olive',
  'Lime',
  'Gray',
  'Alloy',
  'Violet',
  'Multi',
  'Blue',
  'Red',
  'Black',
  'Bronze',
];
